export const BATALKAN_PESANAN_USER = 'BATALKAN_PESANAN_USER';
export const BATALKAN_PESANAN_USER_FAIL = 'BATALKAN_PESANAN_USER_FAIL';
export const BATALKAN_PESANAN_USER_SUCCESS = 'BATALKAN_PESANAN_USER_SUCCESS';

export const PESAN = 'PESAN';
export const PESAN_FAIL = 'PESAN_FAIL';
export const PESAN_SUCCESS = 'PESAN_SUCCESS';

export const GOTO_HOME = 'GOTO_HOME';
export const GOTO_SHOW_LOCATION = 'GOTO_SHOW_LOCATION';
export const GOTO_CARI_TERAPIS = 'GOTO_CARI_TERAPIS';

export const INSERT_LOG = 'INSERT_LOG';
export const SYNC_LOG = 'SYNC_LOG';

export const UPDATE_ID_PESANAN = 'UPDATE_ID_PESANAN';
